name: Dev Workflow

on:
  push:
    branches-ignore:
      - xlink_upstream
  pull_request:
    branches-ignore:
      - xlink_upstream



jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        compiler: [default]
        libusb: [true, false]
        include:
          - os: windows-latest
            compiler: mingw
            libusb: true
          - os: windows-latest
            compiler: mingw
            libusb: false

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install libusb
      if: matrix.os == 'macos-latest' && matrix.libusb == true
      run: |
        brew install libusb

    - name: Install libusb
      if: matrix.os == 'ubuntu-latest' && matrix.libusb == true
      run: |
        sudo apt-get install libusb-1.0-0-dev libusb-1.0-0

    - name: Setup MinGW compiler
      if: matrix.compiler == 'mingw'
      run: |
        choco install mingw
        choco upgrade mingw

    - name: configure
      if: matrix.compiler == 'default'
      run: cmake . -Bbuild -DXLINK_BUILD_EXAMPLES=ON -DXLINK_BUILD_TESTS=ON -DXLINK_ENABLE_LIBUSB=${{ matrix.shared}}

    - name: configure
      if: matrix.compiler == 'mingw'
      run: cmake . -Bbuild -DXLINK_BUILD_EXAMPLES=ON -DXLINK_BUILD_TESTS=ON -DXLINK_ENABLE_LIBUSB=${{ matrix.shared}} -G"MinGW Makefiles"

    - name: build
      run: cmake --build build --parallel
